// default package
// Generated 2014-12-16 20:05:31 by Hibernate Tools 4.3.1

/**
 * Appuser generated by hbm2java
 */

package com.leeyonsoft.clonepintrest.models;

public class UserEntity implements java.io.Serializable {

	private Integer id;
	private String name;
	private String pass;
	private String displayName;

	public UserEntity() {
	}

	public UserEntity(String name, String pass, String displayName) {
		this.name = name;
		this.pass = pass;
		this.displayName = displayName;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getPass() {
		return this.pass;
	}

	public void setPass(String pass) {
		this.pass = pass;
	}

	public String getDisplayName() {
		return this.displayName;
	}

	public void setDisplayName(String displayName) {
		this.displayName = displayName;
	}

}
