// default package
// Generated 2014-12-16 20:05:31 by Hibernate Tools 4.3.1

/**
 * Appuserphoto generated by hbm2java
 */

package com.leeyonsoft.clonepintrest.models;

public class UserPhotoEntity implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -7648966878511820104L;
	
	private Integer id;
	private int userId;
	private int photoId;
	private boolean isOwner;
	private boolean isPublic;

	public UserPhotoEntity() {
	}

	public UserPhotoEntity(int userId, int photoId, boolean isOwner,
			boolean isPublic) {
		this.userId = userId;
		this.photoId = photoId;
		this.isOwner = isOwner;
		this.isPublic = isPublic;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	public int getPhotoId() {
		return this.photoId;
	}

	public void setPhotoId(int photoId) {
		this.photoId = photoId;
	}

	public boolean isIsOwner() {
		return this.isOwner;
	}

	public void setIsOwner(boolean isOwner) {
		this.isOwner = isOwner;
	}

	public boolean isIsPublic() {
		return this.isPublic;
	}

	public void setIsPublic(boolean isPublic) {
		this.isPublic = isPublic;
	}

}
